//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TakasApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TakasDBEntities2 : DbContext
    {
        public TakasDBEntities2()
            : base("name=TakasDBEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TableOffer> TableOffer { get; set; }
        public virtual DbSet<TableProduct> TableProduct { get; set; }
        public virtual DbSet<TableUser> TableUser { get; set; }
    }
}
