//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TakasApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TableUser
    {
        public int UserID { get; set; }

        [Required(ErrorMessage ="Kullanýcý adý boþ býrakýlamaz.")]
        public string UserName { get; set; }

        [Required(ErrorMessage = "Þifre boþ býrakýlamaz.")]
        public string UserPassword { get; set; }
        public System.DateTime UserRegisterDate { get; set; }
    }
}
