//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TakasApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableOffer
    {
        public int OfferID { get; set; }
        public int OfferSenderID { get; set; }
        public int OfferRecieverID { get; set; }
        public string OfferProductID1 { get; set; }
        public string OfferProductID2 { get; set; }
    }
}
