//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TakasApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableProduct
    {
        public int ProductID { get; set; }
        public string ProductTitle { get; set; }
        public int ProductCity { get; set; }
        public int ProductPrice { get; set; }
        public System.DateTime ProductAddDate { get; set; }
        public int ProductUser { get; set; }
        public string ProductPhotoURLS { get; set; }
        public string ProductDescription { get; set; }
    }
}
